# Generated by Django 4.2.1 on 2023-05-26 11:27

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ask_question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("date_posted", models.DateTimeField()),
                ("questions", models.TextField()),
                ("id_ask", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seller",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("price", models.IntegerField()),
                ("product_name", models.CharField(max_length=70)),
                ("img", models.ImageField(upload_to="static/img_product")),
                ("description", models.TextField()),
                ("slug", models.CharField(default="", max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="proflie_users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("phone_no", models.IntegerField()),
                ("profile_pic", models.ImageField(upload_to="static/profile_pic")),
                ("location", models.CharField(max_length=80)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "male"),
                            ("female", "female"),
                            ("others", "others"),
                        ],
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", django_google_maps.fields.AddressField(max_length=200)),
                (
                    "geolocation",
                    django_google_maps.fields.GeoLocationField(max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="reply_ask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_reply", models.IntegerField()),
                ("username", models.CharField(max_length=100)),
                ("date_posted", models.DateTimeField()),
                ("reply", models.TextField()),
                (
                    "comment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.ask_question",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ask_question",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.product",
            ),
        ),
    ]
