# Generated by Django 4.0.6 on 2022-07-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pirce',
            new_name='price',
        ),
    ]
