# Generated by Django 4.0.6 on 2022-07-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='proflie_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('profile_pic', models.ImageField(upload_to='profile_pic')),
                ('location', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=6)),
            ],
        ),
    ]
