# Generated by Django 4.0.6 on 2022-07-09 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        ('backend', '0005_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='static/img_product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default='free', on_delete=django.db.models.deletion.CASCADE, to='account.emailaddress'),
        ),
        migrations.AlterField(
            model_name='proflie_users',
            name='profile_pic',
            field=models.ImageField(upload_to='static/profile_pic'),
        ),
    ]
