# Generated by Django 4.0.6 on 2022-07-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='ask_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('date_posted', models.DateField()),
                ('questions', models.TextField()),
            ],
        ),
    ]
