# Generated by Django 4.0.6 on 2022-07-12 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_ask_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask_question',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AlterField(
            model_name='ask_question',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
