# Generated by Django 4.0.6 on 2022-07-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_ask_question_post_alter_ask_question_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask_question',
            name='date_posted',
            field=models.DateTimeField(),
        ),
    ]
