# Generated by Django 4.0.6 on 2022-07-12 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_ask_question_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask_question',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
    ]
