# Generated by Django 4.0.6 on 2022-07-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_ask_question_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='reply_ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField()),
                ('reply', models.TextField()),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ask_question')),
            ],
        ),
    ]
