# Generated by Django 4.0.6 on 2022-07-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_reply_ask'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask_question',
            name='id_ask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ask_question'),
        ),
    ]
