# Generated by Django 4.0.4 on 2022-08-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_ask_question_id_ask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask_question',
            name='id_ask',
        ),
        migrations.AddField(
            model_name='reply_ask',
            name='username',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
