# Generated by Django 4.0.4 on 2022-08-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_remove_ask_question_id_ask_reply_ask_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask_question',
            name='id_ask',
            field=models.CharField(default='hey', max_length=100),
            preserve_default=False,
        ),
    ]
