# Generated by Django 4.0.4 on 2022-08-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_reply_ask_id_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply_ask',
            name='id_reply',
            field=models.IntegerField(),
        ),
    ]
